### ISSUE TITLE
Forward Solidus Invalid In Filesystem Paths

### ISSUE THREAD

**Issue by roke-julian-lockhart** [stephenberry/JSONC#1]
**https://github.com/json5/json5-spec/issues/46#issue-2034490551**

<blockQuote>

I use JSON5 for filesystem object names. It works brilliantly, allowing me to encode attributes in a standardized manner without using the XDG filesystem object attribute specification (see https://wiki.archlinux.org/title/Extended_attributes). However, I cannot use comments, because they are exclusively delimited by the forward solidus, the sole character disallowed by every kernel and filesystem universally (my configuration is Linux and BTRFS, where literally solely `/` and NULL are disallowed, per https://forum.garudalinux.org/t/btrfs-can-have-crazy-file-names-having/5687/15?u=rokejulianlockhart). Could you provide an alternative, like PowerShell's `#` and `<#` `#>`? I really don't want to go non-standard.

As an example:

> ```.txt
> .	`{title: "[LSHW](https%3A%2F%2Fdownload.opensuse.org%2Frepositories%2Fhardware%2FopenSUSE_Tumbleweed%2Fx86_64%2F)" ⁄* https%3A%2F%2Fdub.sh%2Fs5gs6l *⁄,	id: ""}`{.JSON5}.dir
> ```

To alleviate confusion, that JSON5 is wrapped in Pandoc Markdown for irrelevant reasons. Currently, I must use:

> ```.txt
> .	`{title: "[LSHW](https%3A%2F%2Fdownload.opensuse.org%2Frepositories%2Fhardware%2FopenSUSE_Tumbleweed%2Fx86_64%2F)",	id: ""}`{.JSON5} .dir
> ```

...which syntactically provides less contextual relevance. Is this rationale enough to suggest this?

**Comment by stephenberry** [comment]
I could see adding support for another comment type, but it isn't a top priority, as comments could be embedded in the JSON.

I think the html syntax works: `<!-- ... -->`, I tend to prefer this because it is ubiquitous and annoying to write, so users will only do this if necessary.

However, I do think this shouldn't be considered JSONC, but another standard.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/stephenberry/JSONC/issues/1#issuecomment-1854837486

Do HTML comments work because JSON has a relationship with JS? I've never heard of them working, but if they are standard, that's the solution I need. Thank you!

**Comment by stephenberry** [comment]
@RokeJulianLockhart, HTML comments are not part of JSON. They have to be supported in whatever library is handling JSON. I originally thought this issue was posted on my [glaze](https://github.com/stephenberry/glaze) library for JSON, where support for these comments could be added.
The only way to comment in pure JSON is to add it as a field in an object.
This JSONC specification is supported by Visual Studio Code and others.
